In [23]:
import cv2
import numpy as np

In [24]:
objPoints_total = []
imgPoints_total = []

In [ ]:
# frame 1
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.25,0,0], # cone left
    [-5.25,0,0], # cone left
    [-5.25,0,0], # cone left
    [-5.25,0,0], # cone left

    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.65], # cone front 3d
    [0,-0.3,-6.65],
    [0,-0.3,-6.65],
    [0,-0.3,-6.65]

    # [-6.59,0,0.3],  # cone back
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 

    
], dtype=np.float32).reshape((-1,3))

imgpoints_frame1 = np.array([
    # [883,553], # center
    # [1196,648], # sin
    # [459,625], # cos
    # [1236,494], # - cos
    # [639,479], # front
    # [1235,494], # cone left
    # [383,636], # cone right
    # [550,452]
    [1048.49145507813,474.3056335449221],[1048.59411621094,474.320220947266],[1048.40356445313,474.365905761719],[1048.38012695313,474.314697265625],  # origin
    [733.102661132813,578.699279785156],[733.022216796875,578.696899414063],[733.082580566406,578.690124511719],[733.107360839844,578.702697753906], #sin
    # [444,618],[444.159790039063,618.090270996094],[444.014221191406,618.138854980469],[444.197906494141,618.080993652344], # cos
    # [1240,492],[1239.87170410156,491.924835205078],[1239.26245117188,491.807312011719],[1239.53808593750,491.821746826172], # -cos
    [1293.48901367188,392.305633544922],[1293.54882812500,392.297607421875],[1293.62854003906,392.193267822266],[1293.63281250000,392.272979736328], #front
    [1582.69677734375,509.300720214844],[1582.69616699219,509.297851562500],[1582.68847656250,509.303131103516],[1582.69702148438,509.327270507813], # cone left  
    [628.496337890625,415.709045410156],[628.480590820313,415.732238769531], [628.499755859375,415.723083496094],[628.462707519531,415.712127685547],# cone right
    [730.100219726563,269.303192138672],[729.619201660156,269.327880859375],[729.124450683594,269.368469238281],[728.805603027344,269.395629882813], # stick
    [1391.49877929688,331.498779296875],[1391.47705078125,331.497314453125],[1391.48852539063,331.470092773438],[1391.48132324219,331.540496826172]
    # # [1458,686],[1458.01831054688,686.012634277344],[1457.98693847656,685.982727050781],[1458.00134277344,686.028015136719], # cone back
    # # [1444,716],[1443.99829101563,716.018798828125],[1444.01013183594,716.025329589844],[1444.01208496094,716.046264648438], # cone back floor
    # # [544,420],[544.034240722656,419.994415283203],[544.018859863281,420.002319335938],[544.013977050781,420.024871826172] # cone front
    # [550,452],[550.031372070313,452.006134033203],[550.024597167969,452.025634765625],[550.032714843750,452.007812500000] # cone front floor
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [25]:
# frame 1 
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.4,-0.3,0], # cone left
    [-5.4,-0.3,0], # cone left
    [-5.4,-0.3,0], # cone left
    [-5.4,-0.3,0], # cone left

    [5.25,0,0], # cone right
    [5.25,0,0], # cone right
    [5.25,0,0], # cone right
    [5.25,0,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.54], # cone front
    [0,-0.3,-6.54],
    [0,-0.3,-6.54],
    [0,-0.3,-6.54]
   
], dtype=np.float32).reshape((-1,3))  

# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame1 = np.array([
    # [883,553], # center
    # [1196,648], # sin
    # [459,625], # cos
    # [1236,494], # - cos
    # [639,479], # front
    # [1235,494], # cone left
    # [383,636], # cone right
    # [550,452]
    [1048.49145507813,474.3056335449221],[1048.59411621094,474.320220947266],[1048.40356445313,474.365905761719],[1048.38012695313,474.314697265625],  # origin
    [733.102661132813,578.699279785156],[733.022216796875,578.696899414063],[733.082580566406,578.690124511719],[733.107360839844,578.702697753906], #sin
    # [444,618],[444.159790039063,618.090270996094],[444.014221191406,618.138854980469],[444.197906494141,618.080993652344], # cos
    # [1240,492],[1239.87170410156,491.924835205078],[1239.26245117188,491.807312011719],[1239.53808593750,491.821746826172], # -cos
    [1293.48901367188,392.305633544922],[1293.54882812500,392.297607421875],[1293.62854003906,392.193267822266],[1293.63281250000,392.272979736328], #front
    [1582.69677734375,509.300720214844],[1582.69616699219,509.297851562500],[1582.68847656250,509.303131103516],[1582.69702148438,509.327270507813], # cone left  
    [628.496337890625,415.709045410156],[628.480590820313,415.732238769531], [628.499755859375,415.723083496094],[628.462707519531,415.712127685547],# cone right
    [730.100219726563,269.303192138672],[729.619201660156,269.327880859375],[729.124450683594,269.368469238281],[728.805603027344,269.395629882813], # stick
    [1391.49877929688,331.498779296875],[1391.47705078125,331.497314453125],[1391.48852539063,331.470092773438],[1391.48132324219,331.540496826172]
    # # [1458,686],[1458.01831054688,686.012634277344],[1457.98693847656,685.982727050781],[1458.00134277344,686.028015136719], # cone back
    # # [1444,716],[1443.99829101563,716.018798828125],[1444.01013183594,716.025329589844],[1444.01208496094,716.046264648438], # cone back floor
    # # [544,420],[544.034240722656,419.994415283203],[544.018859863281,420.002319335938],[544.013977050781,420.024871826172] # cone front
    # [550,452],[550.031372070313,452.006134033203],[550.024597167969,452.025634765625],[550.032714843750,452.007812500000] # cone front floor
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [ ]:
# frame 1 
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left

    [5.2,-0.3,0], # cone right
    [5.2,-0.3,0], # cone right
    [5.2,-0.3,0], # cone right
    [5.2,-0.3,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.54], # cone front
    [0,-0.3,-6.54],
    [0,-0.3,-6.54],
    [0,-0.3,-6.54]
   
], dtype=np.float32).reshape((-1,3))  

# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame1 = np.array([
    # [883,553], # center
    # [1196,648], # sin
    # [459,625], # cos
    # [1236,494], # - cos
    # [639,479], # front
    # [1235,494], # cone left
    # [383,636], # cone right
    # [550,452]
    [1048.49145507813,474.3056335449221],[1048.59411621094,474.320220947266],[1048.40356445313,474.365905761719],[1048.38012695313,474.314697265625],  # origin
    [733.102661132813,578.699279785156],[733.022216796875,578.696899414063],[733.082580566406,578.690124511719],[733.107360839844,578.702697753906], #sin
    # [444,618],[444.159790039063,618.090270996094],[444.014221191406,618.138854980469],[444.197906494141,618.080993652344], # cos
    # [1240,492],[1239.87170410156,491.924835205078],[1239.26245117188,491.807312011719],[1239.53808593750,491.821746826172], # -cos
    [1293.48901367188,392.305633544922],[1293.54882812500,392.297607421875],[1293.62854003906,392.193267822266],[1293.63281250000,392.272979736328], #front
    [1582.69677734375,509.300720214844],[1582.69616699219,509.297851562500],[1582.68847656250,509.303131103516],[1582.69702148438,509.327270507813], # cone left  
    [615.092895507813,383.704162597656],[615.093322753906,383.669769287109], [615.087158203125,383.673400878906],[615.099548339844,383.693572998047],# cone right
    [730.100219726563,269.303192138672],[729.619201660156,269.327880859375],[729.124450683594,269.368469238281],[728.805603027344,269.395629882813], # stick
    [1391.49877929688,331.498779296875],[1391.47705078125,331.497314453125],[1391.48852539063,331.470092773438],[1391.48132324219,331.540496826172]
    # # [1458,686],[1458.01831054688,686.012634277344],[1457.98693847656,685.982727050781],[1458.00134277344,686.028015136719], # cone back
    # # [1444,716],[1443.99829101563,716.018798828125],[1444.01013183594,716.025329589844],[1444.01208496094,716.046264648438], # cone back floor
    # # [544,420],[544.034240722656,419.994415283203],[544.018859863281,420.002319335938],[544.013977050781,420.024871826172] # cone front
    # [550,452],[550.031372070313,452.006134033203],[550.024597167969,452.025634765625],[550.032714843750,452.007812500000] # cone front floor
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [26]:
objPoints_total = np.array(objPoints_total, dtype=np.float32)  
imgPoints_total = np.array(imgPoints_total, dtype=np.float32)  

In [27]:
# 3. Camera intrinsics 
K = np.array([[3.66103164e+03,0.00000000e+00,9.28913019e+02],
 [0.00000000e+00,3.68958497e+03,6.24886883e+02],
 [0.00000000e+00,0.00000000e+00,1.00000000e+00]])
distortion = np.array([2.39328104e-01, 7.46320042e-01, 1.44937365e-02, 1.83144030e-03,
  6.18924936e+00])

In [28]:
# 4. Solve for extrinsics
# 4. Solve for extrinsics
ret, rvec, tvec = cv2.solvePnP(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    flags=cv2.SOLVEPNP_SQPNP
)
cv2.solvePnPRefineLM(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    rvec,
    tvec
)

print("Rotation vector (rvec):", rvec)
print("Translation vector (tvec):", tvec)

R, _ = cv2.Rodrigues(rvec)
print("Rotation matrix (R):\n", R)

Rotation vector (rvec): [[ 0.07749696]
 [-2.48517524]
 [-0.33000408]]
Translation vector (tvec): [[ 1.09289338]
 [-1.39584485]
 [34.06277511]]
Rotation matrix (R):
 [[-0.80429255  0.02258617 -0.59380414]
 [-0.13316538  0.96701216  0.21715077]
 [ 0.57912043  0.2537269  -0.77475299]]


In [29]:
# reprojection error
# reprojection error
proj_points, _ = cv2.projectPoints(
    objPoints_total, rvec, tvec, K, distortion
)

proj_points = proj_points.reshape(-1, 2)

error = np.linalg.norm(proj_points - imgPoints_total, axis=1)
print("Reprojection error per point (px):", error)
print("Mean reprojection error (px):", error.mean())



Reprojection error per point (px): [2.1839921 2.2875829 2.110154  2.0764856 7.9189625 7.986125  7.931194
 7.9167805 3.377913  3.3176067 3.2298205 3.2317119 4.152186  4.1520915
 4.1435905 4.147833  8.603806  8.584816  8.605114  8.57009   3.306057
 3.132275  3.0088327 2.969803  5.2977014 5.319421  5.307862  5.315568 ]
Mean reprojection error (px): 4.935192


In [30]:
ret, rvec, tvec, inliers = cv2.solvePnPRansac(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    None,
    None,
    False,
    500,
    20.0,
    0.99,
    cv2.SOLVEPNP_ITERATIVE
)

objPoints_inliers = objPoints_total[inliers[:,0]]
imgPoints_inliers = imgPoints_total[inliers[:,0]]
cv2.solvePnPRefineLM(objPoints_inliers, imgPoints_inliers, K, distortion, rvec, tvec)

# ret,rvec, tvec = cv2.solvePnP(
#     objPoints_total,
#     imgPoints_total,
#     K,
#     distortion,
#     flags=cv2.SOLVEPNP_ITERATIVE)

# cv2.solvePnPRefineLM(objPoints_total, imgPoints_total, K, distortion, rvec, tvec)

(array([[ 0.07749696],
        [-2.48517524],
        [-0.33000408]]),
 array([[ 1.09289338],
        [-1.39584485],
        [34.06277512]]))

In [22]:
# reprojection error
# reprojection error
proj_points, _ = cv2.projectPoints(
    objPoints_inliers, rvec, tvec, K, distortion
)

proj_points = proj_points.reshape(-1, 2)

error = np.linalg.norm(proj_points - imgPoints_inliers, axis=1)
print("Reprojection error per point (px):", error)
print("Mean reprojection error (px):", error.mean())



Reprojection error per point (px): [1.9125196 2.0158336 1.8291243 1.8018968 7.37591   7.44739   7.3900228
 7.3731685 3.3992712 3.3389266 3.2487242 3.2526398 4.5808983 4.580849
 4.5722895 4.576131  8.466734  8.447195  8.467655  8.433084  2.1066859
 1.9037709 1.7934967 1.7920634 5.154262  5.175833  5.162545  5.1747823]
Mean reprojection error (px): 4.6704893


In [ ]:
# blue: pixel, red: reprojection

img = cv2.imread("/Users/goal0312/Desktop/thesis/3_calibration/cam3_frame_4549.png")

# Ensure shapes
imgpoints_2d = imgPoints_inliers.reshape(-1, 2)
proj_points_2d = proj_points.reshape(-1, 2)

for i, (p_meas, p_proj) in enumerate(zip(imgpoints_2d, proj_points_2d)):
    x_meas, y_meas = int(p_meas[0]), int(p_meas[1])
    x_proj, y_proj = int(p_proj[0]), int(p_proj[1])

    # Draw measured point (blue)
    cv2.circle(img, (x_meas, y_meas), 6, (255, 0, 0), -1)

    # Draw projected point (red)
    cv2.circle(img, (x_proj, y_proj), 6, (0, 0, 255), -1)

    # Draw error line (green)
    cv2.line(img, (x_meas, y_meas), (x_proj, y_proj), (0, 255, 0), 2)

    # Optional: label point index
    cv2.putText(
        img, str(i),
        (x_meas + 5, y_meas - 5),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.5, (255, 255, 255), 1
    )

cv2.imshow("Reprojection Overlay", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

2026-02-27 23:07:12.558 python[87734:14115312] _TIPropertyValueIsValid called with 4 on nil context!
2026-02-27 23:07:12.558 python[87734:14115312] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2026-02-27 23:07:12.558 python[87734:14115312] Text input context does not respond to _valueForTIProperty:


In [5]:
imgpoints_frame1

array([[1048.4915 ,  474.30563],
       [1048.5941 ,  474.32022],
       [1048.4036 ,  474.3659 ],
       [1048.3801 ,  474.3147 ],
       [ 733.10266,  578.6993 ],
       [ 733.0222 ,  578.6969 ],
       [ 733.0826 ,  578.6901 ],
       [ 733.10736,  578.7027 ],
       [1293.489  ,  392.30563],
       [1293.5488 ,  392.2976 ],
       [1293.6285 ,  392.19327],
       [1293.6328 ,  392.27298],
       [1582.6968 ,  509.30072],
       [1582.6962 ,  509.29785],
       [1582.6885 ,  509.30313],
       [1582.697  ,  509.32727],
       [ 615.0929 ,  383.70416],
       [ 615.0933 ,  383.66977],
       [ 615.08716,  383.6734 ],
       [ 615.09955,  383.69357],
       [ 730.1002 ,  269.3032 ],
       [ 729.6192 ,  269.32788],
       [ 729.12445,  269.36847],
       [ 728.8056 ,  269.39563],
       [1391.4988 ,  331.49878],
       [1391.477  ,  331.4973 ],
       [1391.4885 ,  331.4701 ],
       [1391.4813 ,  331.5405 ]], dtype=float32)

In [13]:
np.mean(imgpoints_frame1[24:28],0)

array([1391.4865 ,  331.50168], dtype=float32)