In [1]:
import cv2
import numpy as np

- frame 1 = (3:43)x50  = 223
- frame 2 = (01:36)*50 = 96
- frame 3 = (02:10) = 130 
- frame 4 = (02:25) = 145
- frame 5 = (02:48) = 168
- frame 6 = (03:26) = 206
- frame 7 = (04:25) = 265
- frame 8 = (04:32) = 272
- frame 9 = (05:05) = 305
- frame 10 = (05:25)= 325

In [2]:
objPoints_total = []
imgPoints_total = []

In [3]:
# frame 1
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left

    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.64], # cone front 3d
    [0,-0.3,-6.64],
    [0,-0.3,-6.64],
    [0,-0.3,-6.64]

    # [-6.59,0,0.3],  # cone back
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 

    
], dtype=np.float32).reshape((-1,3))     

# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame1 = np.array([
    [966.491455078125,420.701721191406],[968.331115722656,421.063568115234],[968.194946289063,421.166046142578],[968.260192871094,421.159973144531],  # origin
    [969.398559570313,304.105133056641],[969.447387695313,304.001403808594],[969.464843750000,304.062866210938],[969.525756835938,304.041290283203], # sin
    # [1490,420],[1489.98974609375,420.121826171875],[1489.90417480469,420.119903564453],[1489.99621582031,420.186614990234], # cos
    # # [968.636779785156,60.0859680175781],[968.808227539063,60.0830688476563],[968.905944824219,60.0753746032715],  # stick,  # stick
    # [452,420],[452.030334472656,420.183746337891],[451.970062255859,420.071502685547],[451.971679687500,420.099670410156], # -cos
    # [1448,258],  # dot right
    # [494,258], # dot left
    # [1470,142], # 
    # [468,142], # 
    [969.298278808594,586.899780273438],[969.119079589844,586.808166503906],[968.828247070313,586.784423828125],[968.938171386719,586.834045410156], # front
    [351.097808837891,387.097808837891],[351.085327148438,387.100372314453],[351.108978271484,387.089874267578],[351.088989257813,387.085357666016], # cone left
    [1567.50366210938,420.097808837891],[1567.48083496094,420.067138671875],[1567.45117187500,420.100891113281],[1567.50964355469,420.083374023438], # cone right
    [968.401000976563,60.1002426147461],[968.541320800781,60.0871200561523],[968.705322265625,60.0856590270996],[968.795043945313,60.0794525146484], # stick
    # [969.293395996094,688.305603027344],[969.300170898438,688.308105468750],[969.293884277344,688.314575195313],[969.293823242188,688.307800292969] # cone front floor
    [969.298278808594,650.100219726563],[969.286743164063,650.076904296875],[969.292541503906,650.102416992188],[969.300537109375,650.082153320313] # cone front 3d
    # [970,220],[970.059326171875,219.990676879883],[970.122558593750,220.009109497070],[970.162109375000,220.001098632813], # cone back
    # [970,648],[969.989318847656,647.976867675781],[970.004272460938,648.008056640625],[970.015319824219,647.986511230469]
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [ ]:
# frame 1
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.25,0,0], # cone left
    [-5.25,0,0], # cone left
    [-5.25,0,0], # cone left
    [-5.25,0,0], # cone left

    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.65], # cone front 3d
    [0,-0.3,-6.65],
    [0,-0.3,-6.65],
    [0,-0.3,-6.65]

    # [-6.59,0,0.3],  # cone back
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 

    
], dtype=np.float32).reshape((-1,3))     

# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame1 = np.array([
    [966.491455078125,420.701721191406],[968.331115722656,421.063568115234],[968.194946289063,421.166046142578],[968.260192871094,421.159973144531],  # origin
    [969.398559570313,304.105133056641],[969.447387695313,304.001403808594],[969.464843750000,304.062866210938],[969.525756835938,304.041290283203], # sin
    # [1490,420],[1489.98974609375,420.121826171875],[1489.90417480469,420.119903564453],[1489.99621582031,420.186614990234], # cos
    # # [968.636779785156,60.0859680175781],[968.808227539063,60.0830688476563],[968.905944824219,60.0753746032715],  # stick,  # stick
    # [452,420],[452.030334472656,420.183746337891],[451.970062255859,420.071502685547],[451.971679687500,420.099670410156], # -cos
    # [1448,258],  # dot right
    # [494,258], # dot left
    # [1470,142], # 
    # [468,142], # 
    [969.298278808594,586.899780273438],[969.119079589844,586.808166503906],[968.828247070313,586.784423828125],[968.938171386719,586.834045410156], # front
    [366.501220703125,421.300720214844],[366.523925781250,421.302490234375],[366.551116943359,421.326721191406],[366.558471679688,421.319000244141], # cone left
    [1567.50366210938,420.097808837891],[1567.48083496094,420.067138671875],[1567.45117187500,420.100891113281],[1567.50964355469,420.083374023438], # cone right
    [968.401000976563,60.1002426147461],[968.541320800781,60.0871200561523],[968.705322265625,60.0856590270996],[968.795043945313,60.0794525146484], # stick
    # [969.293395996094,688.305603027344],[969.300170898438,688.308105468750],[969.293884277344,688.314575195313],[969.293823242188,688.307800292969] # cone front floor
    [969.298278808594,650.100219726563],[969.286743164063,650.076904296875],[969.292541503906,650.102416992188],[969.300537109375,650.082153320313] # cone front 3d
    # [970,220],[970.059326171875,219.990676879883],[970.122558593750,220.009109497070],[970.162109375000,220.001098632813], # cone back
    # [970,648],[969.989318847656,647.976867675781],[970.004272460938,648.008056640625],[970.015319824219,647.986511230469]
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [4]:
objPoints_total = np.array(objPoints_total, dtype=np.float32)  
imgPoints_total = np.array(imgPoints_total, dtype=np.float32)  

In [5]:
# 3. Camera intrinsics 
K = np.array([[2.70085319e+03, 0.00000000e+00, 9.54201424e+02],
 [0.00000000e+00, 2.72617130e+03, 4.84292906e+02],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
distortion = np.array([0.09386598,0.45834963,0.01126082,0.00248931,0.51257668])

In [6]:
# 4. Solve for extrinsics
ret, rvec, tvec = cv2.solvePnP(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    flags=cv2.SOLVEPNP_ITERATIVE
)
cv2.solvePnPRefineLM(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    rvec,
    tvec
)
print("Rotation vector (rvec):", rvec)
print("Translation vector (tvec):", tvec)

R, _ = cv2.Rodrigues(rvec)
print("Rotation matrix (R):\n", R)

Rotation vector (rvec): [[ 0.28800503]
 [ 0.00447969]
 [-0.00073249]]
Translation vector (tvec): [[ 0.12268566]
 [-0.5567428 ]
 [23.604607  ]]
Rotation matrix (R):
 [[ 9.99989769e-01  1.36304007e-03  4.31324865e-03]
 [-8.17624450e-05  9.58812239e-01 -2.84040636e-01]
 [-4.52275437e-03  2.84037377e-01  9.58802541e-01]]


In [7]:
# reprojection error
# reprojection error
proj_points, _ = cv2.projectPoints(
    objPoints_total, rvec, tvec, K, distortion
)

proj_points = proj_points.reshape(-1, 2)

error = np.linalg.norm(proj_points - imgPoints_total, axis=1)
print("Reprojection error per point (px):", error)
print("Mean reprojection error (px):", error.mean())



Reprojection error per point (px): [1.8666743  1.0281373  1.1270597  1.1204526  1.9614476  2.0682895
 2.0388176  2.0984428  0.79254854 0.5974367  0.4127798  0.5047227
 1.4404163  1.4505589  1.4338638  1.4537945  1.2029291  1.2411219
 1.2345376  1.2103848  1.7158452  1.7315304  1.777111   1.8028508
 0.3366762  0.33758453 0.33055788 0.3469905 ]
Mean reprojection error (px): 1.2379844


In [8]:
ret, rvec, tvec, inliers = cv2.solvePnPRansac(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    None,
    None,
    False,
    500,
    20.0,
    0.99,
    cv2.SOLVEPNP_ITERATIVE
)

objPoints_inliers = objPoints_total[inliers[:,0]]
imgPoints_inliers = imgPoints_total[inliers[:,0]]
cv2.solvePnPRefineLM(objPoints_inliers, imgPoints_inliers, K, distortion, rvec, tvec)


(array([[ 0.28800503],
        [ 0.00447969],
        [-0.00073249]]),
 array([[ 0.12268566],
        [-0.5567428 ],
        [23.604607  ]]))

In [9]:
# reprojection error
# reprojection error
proj_points, _ = cv2.projectPoints(
    objPoints_inliers, rvec, tvec, K, distortion
)

proj_points = proj_points.reshape(-1, 2)

error = np.linalg.norm(proj_points - imgPoints_inliers, axis=1)
print("Reprojection error per point (px):", error)
print("Mean reprojection error (px):", error.mean())



Reprojection error per point (px): [1.8666743  1.0281373  1.1270597  1.1204526  1.9614476  2.0682895
 2.0388176  2.0984428  0.79254854 0.5974367  0.4127798  0.5047227
 1.4404163  1.4505589  1.4338638  1.4537945  1.2029291  1.2411219
 1.2345376  1.2103848  1.7158452  1.7315304  1.777111   1.8028508
 0.3366762  0.33758453 0.33055788 0.3469905 ]
Mean reprojection error (px): 1.2379844


In [11]:
rvec,tvec

(array([[ 1.41556113],
        [ 1.42056942],
        [-1.06358585]]),
 array([[ 0.10839826],
        [-0.55580243],
        [23.96330397]]))

In [ ]:
# blue: pixel, red: reprojection

img = cv2.imread("/Users/goal0312/Desktop/thesis/3_calibration/cam1.png")

# Ensure shapes
imgpoints_2d = imgPoints_inliers.reshape(-1, 2)
proj_points_2d = proj_points.reshape(-1, 2)

for i, (p_meas, p_proj) in enumerate(zip(imgpoints_2d, proj_points_2d)):
    x_meas, y_meas = int(p_meas[0]), int(p_meas[1])
    x_proj, y_proj = int(p_proj[0]), int(p_proj[1])

    # Draw measured point (blue)
    cv2.circle(img, (x_meas, y_meas), 6, (255, 0, 0), -1)

    # Draw projected point (red)
    cv2.circle(img, (x_proj, y_proj), 6, (0, 0, 255), -1)

    # Draw error line (green)
    cv2.line(img, (x_meas, y_meas), (x_proj, y_proj), (0, 255, 0), 2)

    # Optional: label point index
    cv2.putText(
        img, str(i),
        (x_meas + 5, y_meas - 5),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.5, (255, 255, 255), 1
    )

cv2.imshow("Reprojection Overlay", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

2026-02-27 23:55:53.365 python[90746:14159350] _TIPropertyValueIsValid called with 4 on nil context!
2026-02-27 23:55:53.365 python[90746:14159350] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2026-02-27 23:55:53.365 python[90746:14159350] Text input context does not respond to _valueForTIProperty:
2026-02-27 23:56:08.955 python[90746:14159350] _TIPropertyValueIsValid called with 4 on nil context!
2026-02-27 23:56:08.955 python[90746:14159350] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2026-02-27 23:56:08.955 python[90746:14159350] Text input context does not respond to _valueForTIProperty:


In [13]:
import numpy as np
imgpoints = np.array([
    [966.491455078125,420.701721191406],[968.331115722656,421.063568115234],[968.194946289063,421.166046142578],[968.260192871094,421.159973144531],  # origin
    [969.398559570313,304.105133056641],[969.447387695313,304.001403808594],[969.464843750000,304.062866210938],[969.525756835938,304.041290283203], # sin
    # [1490,420],[1489.98974609375,420.121826171875],[1489.90417480469,420.119903564453],[1489.99621582031,420.186614990234], # cos
    # # [968.636779785156,60.0859680175781],[968.808227539063,60.0830688476563],[968.905944824219,60.0753746032715],  # stick,  # stick
    # [452,420],[452.030334472656,420.183746337891],[451.970062255859,420.071502685547],[451.971679687500,420.099670410156], # -cos
    # [1448,258],  # dot right
    # [494,258], # dot left
    # [1470,142], # 
    # [468,142], # 
    [969.298278808594,586.899780273438],[969.119079589844,586.808166503906],[968.828247070313,586.784423828125],[968.938171386719,586.834045410156], # front
    [366.501220703125,421.300720214844],[366.523925781250,421.302490234375],[366.551116943359,421.326721191406],[366.558471679688,421.319000244141], # cone left
    [1567.50366210938,420.097808837891],[1567.48083496094,420.067138671875],[1567.45117187500,420.100891113281],[1567.50964355469,420.083374023438], # cone right
    [968.401000976563,60.1002426147461],[968.541320800781,60.0871200561523],[968.705322265625,60.0856590270996],[968.795043945313,60.0794525146484], # stick
    # [969.293395996094,688.305603027344],[969.300170898438,688.308105468750],[969.293884277344,688.314575195313],[969.293823242188,688.307800292969] # cone front floor
    [969.298278808594,650.100219726563],[969.286743164063,650.076904296875],[969.292541503906,650.102416992188],[969.300537109375,650.082153320313] # cone front 3d
])

In [15]:
imgpoints

array([[ 966.49145508,  420.70172119],
       [ 968.33111572,  421.06356812],
       [ 968.19494629,  421.16604614],
       [ 968.26019287,  421.15997314],
       [ 969.39855957,  304.10513306],
       [ 969.4473877 ,  304.00140381],
       [ 969.46484375,  304.06286621],
       [ 969.52575684,  304.04129028],
       [ 969.29827881,  586.89978027],
       [ 969.11907959,  586.8081665 ],
       [ 968.82824707,  586.78442383],
       [ 968.93817139,  586.83404541],
       [ 366.5012207 ,  421.30072021],
       [ 366.52392578,  421.30249023],
       [ 366.55111694,  421.32672119],
       [ 366.55847168,  421.31900024],
       [1567.50366211,  420.09780884],
       [1567.48083496,  420.06713867],
       [1567.45117188,  420.10089111],
       [1567.50964355,  420.08337402],
       [ 968.40100098,   60.10024261],
       [ 968.5413208 ,   60.08712006],
       [ 968.70532227,   60.08565903],
       [ 968.79504395,   60.07945251],
       [ 969.29827881,  650.10021973],
       [ 969.28674316,  6

In [26]:
imgpoints[12:16]

array([[366.5012207 , 421.30072021],
       [366.52392578, 421.30249023],
       [366.55111694, 421.32672119],
       [366.55847168, 421.31900024]])

In [32]:
np.mean(imgpoints[24:28],0)

array([969.29452515, 650.09042358])