In [2]:
import cv2
import numpy as np

In [3]:
objPoints_total = []
imgPoints_total = []

In [4]:
# frame 1
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left
    [-5.35,-0.3,0], # cone left

    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.64], # cone front 3d
    [0,-0.3,-6.64],
    [0,-0.3,-6.64],
    [0,-0.3,-6.64]

    # [-6.59,0,0.3],  # cone back
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 

    
], dtype=np.float32).reshape((-1,3))     

# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame1 = np.array([
    # [883,553], # center
    # [1196,648], # sin
    # [459,625], # cos
    # [1236,494], # - cos
    # [639,479], # front
    # [1235,494], # cone left
    # [383,636], # cone right
    # [550,452]
    [884.691955566406,551.303161621094],[885.021789550781,551.359802246094],[884.837402343750,551.349426269531],[884.668945312500,551.340087890625],  # origin
    [1191.68945312500,645.503662109375],[1191.70422363281,645.503662109375],[1191.71057128906,645.526916503906],[1191.70629882813,645.513366699219], #sin
    # [444,618],[444.159790039063,618.090270996094],[444.014221191406,618.138854980469],[444.197906494141,618.080993652344], # cos
    # [1240,492],[1239.87170410156,491.924835205078],[1239.26245117188,491.807312011719],[1239.53808593750,491.821746826172], # -cos
    [641.100219726563,478.701721191406],[640.910156250000,478.596496582031],[641.125610351563,478.630920410156],[641.261840820313,478.611419677734], #front
    [1296.10021972656,455.303192138672],[1296.07885742188,455.299621582031],[1296.11328125000,455.281280517578],[1296.06567382813,455.312835693359], # cone left  
    [380.701721191406,633.508544921875],[380.728454589844,633.496887207031],[380.764923095703,633.484924316406],[380.755432128906,633.505859375000],# cone right
    [1191.89978027344,346.300720214844],[1191.82324218750,346.325439453125],[1191.76037597656,346.356811523438],[1191.80456542969,346.376617431641], # stick
    [542.699279785156,422.100250244141],[542.708618164063,422.114746093750],[542.710205078125,422.099334716797],[542.720275878906,422.109558105469] # cone front
    # # [1458,686],[1458.01831054688,686.012634277344],[1457.98693847656,685.982727050781],[1458.00134277344,686.028015136719], # cone back
    # # [1444,716],[1443.99829101563,716.018798828125],[1444.01013183594,716.025329589844],[1444.01208496094,716.046264648438], # cone back floor
    # # [544,420],[544.034240722656,419.994415283203],[544.018859863281,420.002319335938],[544.013977050781,420.024871826172] # cone front
    # [550,452],[550.031372070313,452.006134033203],[550.024597167969,452.025634765625],[550.032714843750,452.007812500000] # cone front floor
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [ ]:
# frame 1 
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame1 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [0, 0, 4.5],               # sin
    [0, 0, 4.5],
    [0, 0, 4.5],
    [0, 0, 4.5],

    # [0, 4.55, 0],                # cos
    # [0, 4.55, 0],
    # [0, 4.55, 0],
    # [0, 4.55, 0],

    # [0,-4.55,0],                 # -cos
    # [0,-4.55,0],
    # [0,-4.55,0],
    # [0,-4.55,0],

    [0, 0, -4.5],               # front
    [0, 0, -4.5],
    [0, 0, -4.5],
    [0, 0, -4.5],

    [-5.26,-0.3,0], # cone left
    [-5.26,-0.3,0], # cone left
    [-5.26,-0.3,0], # cone left
    [-5.26,-0.3,0], # cone left

    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right
    [5.2,0,0], # cone right

    [0,-2.53,4.5], # stick
    [0,-2.53,4.5],
    [0,-2.53,4.5],
    [0,-2.53,4.5],

    [0,-0.3,-6.55], # cone front
    [0,-0.3,-6.55],
    [0,-0.3,-6.55],
    [0,-0.3,-6.55]
   
], dtype=np.float32).reshape((-1,3))  


# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame1 = np.array([
    # [883,553], # center
    # [1196,648], # sin
    # [459,625], # cos
    # [1236,494], # - cos
    # [639,479], # front
    # [1235,494], # cone left
    # [383,636], # cone right
    # [550,452]
    [884.691955566406,551.303161621094],[885.021789550781,551.359802246094],[884.837402343750,551.349426269531],[884.668945312500,551.340087890625],  # origin
    [1191.68945312500,645.503662109375],[1191.70422363281,645.503662109375],[1191.71057128906,645.526916503906],[1191.70629882813,645.513366699219], #sin
    # [444,618],[444.159790039063,618.090270996094],[444.014221191406,618.138854980469],[444.197906494141,618.080993652344], # cos
    # [1240,492],[1239.87170410156,491.924835205078],[1239.26245117188,491.807312011719],[1239.53808593750,491.821746826172], # -cos
    [641.100219726563,478.701721191406],[640.910156250000,478.596496582031],[641.125610351563,478.630920410156],[641.261840820313,478.611419677734], #front
    [1296.10021972656,455.303192138672],[1296.07885742188,455.299621582031],[1296.11328125000,455.281280517578],[1296.06567382813,455.312835693359], # cone left  
    [380.701721191406,633.508544921875],[380.728454589844,633.496887207031],[380.764923095703,633.484924316406],[380.755432128906,633.505859375000],# cone right
    [1191.89978027344,346.300720214844],[1191.82324218750,346.325439453125],[1191.76037597656,346.356811523438],[1191.80456542969,346.376617431641], # stick
    [543.298278808594,422.2909545898445],[543.307373046875,422.307891845703],[543.308959960938,422.291473388672],[543.318725585938,422.301055908203] # cone front
    # # [1458,686],[1458.01831054688,686.012634277344],[1457.98693847656,685.982727050781],[1458.00134277344,686.028015136719], # cone back
    # # [1444,716],[1443.99829101563,716.018798828125],[1444.01013183594,716.025329589844],[1444.01208496094,716.046264648438], # cone back floor
    # # [544,420],[544.034240722656,419.994415283203],[544.018859863281,420.002319335938],[544.013977050781,420.024871826172] # cone front
    # [550,452],[550.031372070313,452.006134033203],[550.024597167969,452.025634765625],[550.032714843750,452.007812500000] # cone front floor
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame1)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame1)   # append all 2D points from this frame

In [6]:
# frame 6 - perfect
# Define your 3D rink landmarks (in meters) - Ingmar measure
objpoints_frame6 = np.array([
    [0,0,0],                     # origin - center
    [0,0,0],
    [0,0,0],
    [0,0,0],

    [-4.55, 0, 0],               # sin
    [-4.55, 0, 0],               # sin
    [-4.55, 0, 0],               # sin
    [-4.55, 0, 0],               # sin

    [0, 4.55, 0],                # cos
    [0, 4.55, 0],                # cos
    [0, 4.55, 0],                # cos
    [0, 4.55, 0],                # cos

    [0,-4.55,0],                 # -cos
    [0,-4.55,0],                 # -cos
    [0,-4.55,0],                 # -cos
    [0,-4.55,0],                 # -cos

    # [-4.55,0,0],                  # back
    # [-4.55,0,0],                  # back
    # [-4.55,0,0],                  # back
    # [-4.55,0,0],                  # back

    [0,-5.3,0], # cone left
    [0,-5.3,0],
    [0,-5.3,0],
    [0,-5.3,0],

    [0,5.25,0], # cone right
    [0,5.25,0],
    [0,5.25,0],
    [0,5.25,0]
    # [-6.59,0,0.3],  # cone back 
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 
    # [-6.59,0,0.3], 
    # [-6.54,0,0.0],  # cone back floor
    # [-6.54,0,0.0], 
    # [-6.54,0,0.0], 
    # [-6.54,0,0.0], 

    # [6.59,0,0.3],                      # cone front
    # [6.59,0,0.3],      
    # [6.59,0,0.3],  
    # [6.59,0,0.3],      
    # [6.54,0,0],                      # cone front

], dtype=np.float32).reshape((-1,3))     

# 2. Define corresponding 2D points in the camera image (pixels)
imgpoints_frame6 = np.array([
    # [883,553], # center
    # [1196,648], # sin
    # [459,625], # cos
    # [1236,494], # - cos
    # [639,479], # front
    # [1235,494], # cone left
    # [383,636], # cone right
    # [550,452]
    [886,550],[886.234130859375,549.987548828125],[886.396972656250,549.964965820313],[886.251831054688,549.962890625000],  # origin
    [1196,644],[1196.45275878906,644.055908203125],[1196.07336425781,644.082885742188],[1196.49340820313,644.134216308594], #sin
    [450,618],[449.917785644531,617.912414550781],[449.932373046875,617.898071289063],[449.931182861328,617.963928222656], # cos
    [1230,490],[1230.91918945313,490.080352783203],[1229.93884277344,489.964813232422],[1229.67297363281,489.921630859375], # -cos
    [1292,482],[1292.02709960938,482.003448486328],[1292.01538085938,482.006652832031],[1292.01818847656,481.998413085938], # cone left  
    [378,628],[377.987304687500,628.020202636719],[377.963134765625,628.034362792969],[378.003662109375,627.991394042969]# cone right
    # # [1458,686],[1458.01831054688,686.012634277344],[1457.98693847656,685.982727050781],[1458.00134277344,686.028015136719], # cone back
    # # # [1444,716],[1443.99829101563,716.018798828125],[1444.01013183594,716.025329589844],[1444.01208496094,716.046264648438], # cone back floor
    # # [544,420],[544.034240722656,419.994415283203],[544.018859863281,420.002319335938],[544.013977050781,420.024871826172] # cone front
    # [550,452],[550.031372070313,452.006134033203],[550.024597167969,452.025634765625],[550.032714843750,452.007812500000] # cone front floor
    # # [1571,421],            # cone right
    # [370,417],            # cone left
    # [966,687]            # cone close
    # [351,387]
], dtype=np.float32)
objPoints_total.extend(objpoints_frame6)   # append all 3D points from this frame
imgPoints_total.extend(imgpoints_frame6)   # append all 2D points from this frame

In [5]:
objPoints_total = np.array(objPoints_total, dtype=np.float32)  
imgPoints_total = np.array(imgPoints_total, dtype=np.float32)  

In [6]:
# 3. Camera intrinsics 
K = np.array([[3.54548296e+03, 0.00000000e+00, 9.60287866e+02],
                [0.00000000e+00, 3.54924565e+03, 5.57450277e+02],
                [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])
distortion = np.array([5.22080106e-02,5.61495738e+00,1.01498704e-02,2.81631980e-03,-2.88237239e+01])

In [7]:
# 4. Solve for extrinsics
ret, rvec, tvec = cv2.solvePnP(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    flags=cv2.SOLVEPNP_ITERATIVE
)
cv2.solvePnPRefineLM(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    rvec,
    tvec
)
print("Rotation vector (rvec):", rvec)
print("Translation vector (tvec):", tvec)

R, _ = cv2.Rodrigues(rvec)
print("Rotation matrix (R):\n", R)

Rotation vector (rvec): [[0.09639893]
 [2.49858155]
 [0.27288073]]
Translation vector (tvec): [[-0.73166105]
 [-0.050763  ]
 [33.65914114]]
Rotation matrix (R):
 [[-0.80753937  0.00532407  0.58978964]
 [ 0.13250693  0.97603538  0.17261761]
 [-0.57473653  0.21754674 -0.78889248]]


In [8]:
# reprojection error
# reprojection error
proj_points, _ = cv2.projectPoints(
    objPoints_total, rvec, tvec, K, distortion
)

proj_points = proj_points.reshape(-1, 2)

error = np.linalg.norm(proj_points - imgPoints_total, axis=1)
print("Reprojection error per point (px):", error)
print("Mean reprojection error (px):", error.mean())



Reprojection error per point (px): [ 1.6698427  1.9418701  1.7779063  1.6319141  5.1989236  5.212311
  5.227911   5.218293   3.3060715  3.122532   3.335076   3.4722705
 11.513334  11.534841  11.501335  11.547398   7.4849067  7.4569297
  7.4192634  7.431283   3.348033   3.273249   3.2048955  3.2262788
  7.051237   7.0612655  7.062107   7.0726557]
Mean reprojection error (px): 5.6537123


In [9]:
ret, rvec, tvec, inliers = cv2.solvePnPRansac(
    objPoints_total,
    imgPoints_total,
    K,
    distortion,
    None,
    None,
    False,
    8,
    20.0,
    0.99,
    
    cv2.SOLVEPNP_ITERATIVE
)

objPoints_inliers = objPoints_total[inliers[:,0]]
imgPoints_inliers = imgPoints_total[inliers[:,0]]
cv2.solvePnPRefineLM(objPoints_inliers, imgPoints_inliers, K, distortion, rvec, tvec)


(array([[0.09639893],
        [2.49858155],
        [0.27288073]]),
 array([[-0.73166105],
        [-0.050763  ],
        [33.65914115]]))

In [10]:
# reprojection error
# reprojection error
proj_points, _ = cv2.projectPoints(
    objPoints_inliers, rvec, tvec, K, distortion
)

proj_points = proj_points.reshape(-1, 2)

error = np.linalg.norm(proj_points - imgPoints_inliers, axis=1)
print("Reprojection error per point (px):", error)
print("Mean reprojection error (px):", error.mean())



Reprojection error per point (px): [ 1.6698427  1.9418701  1.7779063  1.6319141  5.1989236  5.212311
  5.227911   5.218293   3.3060715  3.122532   3.335076   3.4722705
 11.513334  11.534841  11.501335  11.547398   7.4849067  7.4569297
  7.4192634  7.431283   3.348033   3.273249   3.2048955  3.2262788
  7.051237   7.0612655  7.062107   7.0726557]
Mean reprojection error (px): 5.6537123


In [10]:
proj_points

array([[ 885.1446 ,  552.1917 ],
       [ 885.1446 ,  552.1917 ],
       [ 885.1446 ,  552.1917 ],
       [ 885.1446 ,  552.1917 ],
       [1192.496  ,  644.7217 ],
       [1192.496  ,  644.7217 ],
       [1192.496  ,  644.7217 ],
       [1192.496  ,  644.7217 ],
       [ 637.0984 ,  477.9301 ],
       [ 637.0984 ,  477.9301 ],
       [ 637.0984 ,  477.9301 ],
       [ 637.0984 ,  477.9301 ],
       [1304.9886 ,  457.27945],
       [1304.9886 ,  457.27945],
       [1304.9886 ,  457.27945],
       [1304.9886 ,  457.27945],
       [ 386.72165,  632.1784 ],
       [ 386.72165,  632.1784 ],
       [ 386.72165,  632.1784 ],
       [ 386.72165,  632.1784 ],
       [1195.7623 ,  347.41296],
       [1195.7623 ,  347.41296],
       [1195.7623 ,  347.41296],
       [1195.7623 ,  347.41296],
       [ 538.1551 ,  421.47668],
       [ 538.1551 ,  421.47668],
       [ 538.1551 ,  421.47668],
       [ 538.1551 ,  421.47668]], dtype=float32)

In [ ]:
img = cv2.imread("/Users/goal0312/Desktop/thesis/3_calibration/extrinsic_cam2.jpg")

# Ensure shapes
imgpoints_2d = imgPoints_inliers.reshape(-1, 2)
proj_points_2d = proj_points.reshape(-1, 2)

for i, (p_meas, p_proj) in enumerate(zip(imgpoints_2d, proj_points_2d)):
    x_meas, y_meas = int(p_meas[0]), int(p_meas[1])
    x_proj, y_proj = int(p_proj[0]), int(p_proj[1])

    # Draw measured point (blue)
    cv2.circle(img, (x_meas, y_meas), 6, (255, 0, 0), -1)

    # Draw projected point (red)
    cv2.circle(img, (x_proj, y_proj), 6, (0, 0, 255), -1)

    # Draw error line (green)
    cv2.line(img, (x_meas, y_meas), (x_proj, y_proj), (0, 255, 0), 2)

    # Optional: label point index
    cv2.putText(
        img, str(i),
        (x_meas + 5, y_meas - 5),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.5, (255, 255, 255), 1
    )

cv2.imshow("Reprojection Overlay", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

2026-02-28 00:06:56.963 python[90060:14149990] _TIPropertyValueIsValid called with 4 on nil context!
2026-02-28 00:06:56.963 python[90060:14149990] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2026-02-28 00:06:56.963 python[90060:14149990] Text input context does not respond to _valueForTIProperty:
2026-02-28 00:07:02.225 python[90060:14149990] _TIPropertyValueIsValid called with 4 on nil context!
2026-02-28 00:07:02.225 python[90060:14149990] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2026-02-28 00:07:02.225 python[90060:14149990] Text input context does not respond to _valueForTIProperty:
2026-02-28 00:07:27.814 python[90060:14149990] _TIPropertyValueIsValid called with 4 on nil context!
2026-02-28 00:07:27.814 python[90060:14149990] imkxpc_getApplicationProperty:reply: called with incorrect property value 4, bailing.
2026-02-28 00:07:27.814 python[90060:14149990] Text input context does not respond t

In [13]:
imgpoints = np.array([   [884.691955566406,551.303161621094],[885.021789550781,551.359802246094],[884.837402343750,551.349426269531],[884.668945312500,551.340087890625],  # origin
    [1191.68945312500,645.503662109375],[1191.70422363281,645.503662109375],[1191.71057128906,645.526916503906],[1191.70629882813,645.513366699219], #sin
    # [444,618],[444.159790039063,618.090270996094],[444.014221191406,618.138854980469],[444.197906494141,618.080993652344], # cos
    # [1240,492],[1239.87170410156,491.924835205078],[1239.26245117188,491.807312011719],[1239.53808593750,491.821746826172], # -cos
    [641.100219726563,478.701721191406],[640.910156250000,478.596496582031],[641.125610351563,478.630920410156],[641.261840820313,478.611419677734], #front
    [1296.10021972656,455.303192138672],[1296.07885742188,455.299621582031],[1296.11328125000,455.281280517578],[1296.06567382813,455.312835693359], # cone left  
    [380.701721191406,633.508544921875],[380.728454589844,633.496887207031],[380.764923095703,633.484924316406],[380.755432128906,633.505859375000],# cone right
    [1191.89978027344,346.300720214844],[1191.82324218750,346.325439453125],[1191.76037597656,346.356811523438],[1191.80456542969,346.376617431641], # stick
    [542.699279785156,422.100250244141],[542.708618164063,422.114746093750],[542.710205078125,422.099334716797],[542.720275878906,422.109558105469] # cone front
])

In [20]:
np.mean(imgpoints[24:28],0)

array([542.70959473, 422.10597229])